# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e24d93c6de845038dd8385ed23953d33cdce345e882bb6646ad301a53e2309d081b66707b7f1a97f37a2600192b9ac1029671cb0ef627f3a740137e1a861043e

test:
  secret_key_base: a5babdfe27ef584fb5af3b34ca2f80b2d874b06d941c075f25b5b99525989bae8a3c5ab0e8b23d48d297392fa2fcb9f32ae5f5a4f21b126b2817503cc1331371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
